---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
     interval: "weekly"
    reviewers:
      - "brucellino"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "brucellino"
  - package-ecosystem: "pip"
    directory: ".github/build"
    schedule:
      interval: "weekly"
    reviewers:
      - "brucellino"
