---
name: Release
permissions:
  actions: read
  checks: write
  contents: write
  issues: write
  packages: write
  statuses: write
  security-events: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.16.0
        with:
          path: .github/build/playbook.yml
        env:
          ANSIBLE_ROLES_PATH: "${PWD}/../"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Packer
        run: curl https://releases.hashicorp.com/packer/1.8.7/packer_1.8.7_linux_amd64.zip | gunzip -> packer ; chmod u+x packer
      - name: Get Ansible
        run: pip install ansible
      - name: Init packer
        working-directory: .github/build
        run: ../../packer init .
      - name: Validate Packer template
        working-directory: .github/build
        run: ../../packer validate .
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: add semantic release plugins
        run: |
          npm install -D '@semantic-release/changelog' \
                          '@semantic-release/git'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
